---
- name: Odinstaluj BurpSuite Community Edition
  hosts: localhost
  become: yes  # To umożliwia Ansible uruchomienie poleceń z uprawnieniami roota

  tasks:
    - name: Odinstaluj BurpSuite Community Edition
      ansible.builtin.package:
        name: burpsuite  # Nazwa pakietu Code OSS zależy od systemu operacyjnego
        state: absent
